config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    authenticated do
      root to: 'tasks#index'
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end

  devise_for :users
  resources :tasks, only: %i[show update destroy create index edit new]
  resources :tags, only: %i[index create destroy new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user
  has_many :task_tags, dependent: :destroy
  has_many :tasks, through: :task_tags

  validates :name, presence: true
  validates_uniqueness_of :name, scope: :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_tags, dependent: :destroy
  has_many :tags, through: :task_tags

  validates :title, presence: true
  validates :status, presence: true, inclusion: { in: %w[to_do done],
                                                  message: "%{value} is not a valid status" }
  validates :importance, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5],
                                                      message: "%{value} is not a valid level of importance" }

end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tasks
  has_many :tags

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = current_user.tags
    @tags = ["You dont have any tags yet"] if @tags.nil?
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    @tag.user = current_user

    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: "Tag was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: "Task was successfully created." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private

  def set_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
    @tasks = current_user.tasks
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @tasks, notice: "Flat was successfully created." }
        format.json { render :show, status: :created, location: @flat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    params['user'] = current_user.id
    @filter = TaskFilter.new(params)
    @tasks = @filter.filter!
  end

  def show
  end

  def new
    @tags = current_user.tags
    @task = Task.new
  end

  def create
    @tags = current_user.tags
    @task = Task.new(task_params)
    @task.user = current_user

    respond_to do |format|
      if add_tags && @task.save
        format.html { redirect_to tasks_path, notice: "Task was successfully created." }
      else
        format.html { render :new, notice: "Couldn't create the task, please try again." }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "Task was successfully deleted." }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :status, :importance, :deadline)
  end

  def add_tags
    selected_tags = params['task']['tags']
    return true if selected_tags.nil?
    return false unless selected_tags.size <= 3

    selected_tags.each do |tag_id|
      tag = Tag.find(tag_id.to_i)
      TaskTag.create(tag: tag, task: @task)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>Your tags</h1>

<%unless @tags.present? %>
  <h3>You don't have any tags created yet</h3>
<% end %>
<% @tags.each do |tag| %>
  <%= tag.name %>
<% end %>

<%= link_to 'New Tag', new_tag_path %>
<%= link_to 'My Tasks', tasks_path %>

app/views/tags/new.html.erb
<h1>Creating a new Tag</h1>

<%= form_with(model: @tag) do |form| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
        <% @tag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, ["to_do", "done"]%>
  </div>

  <div class="field">
    <%= form.label :importance %>
    <%= form.number_field :importance, in: 1..5 %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_field :deadline %>
  </div>

  <div class="field">
  <%= form.label :tags %>
  <% @tags.each do |tag| %>
      <%= form.label tag.name %>
      <%= form.check_box :tags, {:multiple => true}, tag.id, nil %>   
  <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %>
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Your Tasks</h1>

<div class="tasks-list">

  <% @tasks.each do |task| %>
    <div class="task-card">
      <div class="task-card-header">
        <span class="task-title"><%= task.title %></span>
        <span class="<%=task.status%>"><%= task.status %></span>
      </div>
      <div class="task-tags">
        <% task.tags.each do |tag| %>
          <span class="tag"><%= tag.name %></span>
        <% end%>
      </div>
      <div class="task-options">
        <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }%>
        <%= link_to 'More info', task%>
      </div>
    </div>
  <% end %>
</div>

<div class="index-filters">
    <h2>Filters</h2>

    <%= simple_form_for :search, url: tasks_path, method: :get do |f| %>
    <div class="form-group filters-box">
      <%= f.input :deadline, as: :string, label: 'Max. deadline', required: false, input_html: { value: @filter.deadline, type: :date } %>
      <%= f.input :importance, label: 'Importance', required: false, input_html: { value: @filter.importance } %>
      <%= f.input :status, collection: ['to_do', 'done'], label: false, prompt: 'Select the status', required: false, class: 'filter-dropdown', input_html: { value: @filter.status }%>
      <%= f.submit 'GO!', name: nil, class: 'red-btn' %>
    </div>
  
    <% end %>
    </div>

<div class="tasks-list-options">
  <%= link_to 'New Task', new_task_path %>
  <%= link_to 'My tags', tags_path %>
  <%= link_to  'Sign out', destroy_user_session_path, method: :delete%>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p>Description: <%= @task.content == "" ? "This task doesn't have a description" : @task.content %></p>
<p>Importance level: <%= @task.importance %></p>
<p>Status: <%= @task.status %></p>
<p>Deadline: <%= @task.deadline%></p>
<div class="task-tags">
  <% @task.tags.each do |tag| %>
    <span class="tag"><%= tag.name %></span>
  <% end%>
</div>

<%= link_to 'Edit', edit_task_path(@task) %>
<%= link_to 'Back', tasks_path %>